### ISSUE TITLE
Ubuntu version unavailable

### ISSUE THREAD

**Issue by zatarain** [omegaup/puppet#3] opened 2017-02-12 23:37 UTC
Ubuntu Wily is no longer available for cloud ubuntu.com. Then, when you try to call "vagrant up" you get a 404 Error from Vagrantfile when trying to get the Ubuntu Wily image for cloud.

I suggest to use a LTS version to avoid this kind of issues.

**Comment by lhchavez** [comment] 2017-02-12 23:39
The issue is that we _also_ need to use the same version that production uses. As you might guess, that is currently Wily.

@joemmanuel think you can help do another migration? :P

**Comment by alanboy** [comment] 2017-02-14 16:33
The bigger problem is that this is blocking new devs from bringing up the VM.

**Comment by lhchavez** [comment] 2017-02-14 16:39
i'm aware. we're working on it.

**Comment by alanboy** [comment] 2017-02-14 16:47
sweet. for your convenience, here is the list of fixes i had to do to get the VM running again:

Bug #A - use ubuntu xenial in Vagrantfile
```
config.vm.box = "omegaup-xenial"
config.vm.box_url = "https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-vagrant.box"
```

Bug #B -  `/home/ubuntu/Puppetfile` is missing, but it's present in `/vagrant`
either create the file `/home/ubuntu/Puppetfile` with the following contents 
```moduledir '/etc/puppet/modules'
mod 'puppetlabs/concat', :latest
mod 'puppetlabs/stdlib', :latest
mod 'puppetlabs/mysql', :latest
mod 'puppetlabs/apt', :latest
mod 'puppet-nginx', :latest
mod 'rafaelfc/pear', :latest
mod 'omegaup', :git => 'https://github.com/omegaup/puppet'
```
or add `cd /vagrant`  to `linux-install.sh` 

Bug #C - `/usr/bin/python` is missing

```cd /usr/bin
sudo ln -s python python2.7
```

Bug #D - Because #A, now `init.pp` user must change to `ubuntu`
`sudo vim /etc/puppet/modules/omegaup/manifests/init.pp`

Bug #E - 12_problemsets.sql': Invalid default value for 'access_time'

```
Error: Execution of '/usr/bin/python3 /opt/omegaup/stuff/db-migrate.py --config-file=/root/.my.cnf migrate --development-environment' returned 1: ERROR 1067 (42000) at line 85 in file: '/opt/omegaup/frontend/database/12_problemsets.sql': Invalid default value for 'access_time'
```

**Comment by joemmanuel** [comment] 2017-02-15 01:28
OK folks, I've started the prod upgrade yoga, but last time took us 1-2 months to get prod upgraded.

While full support for Xenial lands, here is a *temporal* _verified_ not ideal workaround to bootstrap Wily. Note that this is grabbing a unofficial Vagrant image from somebody else's repo on Atlassian, be aware of the risks that might imply.

1: On Vagrant file, use `config.vm.box = "wzurowski/wily64"` and comment out `config.vm.box_url` 
2. `vagrant up`
3. Wait until fails, do `vagrant ssh` and apply winftw fixes:
```
sudo apt-get update
cp /vagrant/Puppetfile /home/vagrant/.
sudo apt-get -y install python-software-properties
sudo apt-get -y install software-properties-common
sudo apt-key adv --recv-key --keyserver keyserver.ubuntu.com EB34503029923428
sudo apt-get update
```
4. While !success, `vagrant provision`
5. Open `localhost:8080`

**Comment by joemmanuel** [comment] 2017-02-15 01:35
BTW would be much better if somebody with a working Wily setup shares the image _privately_ to avoid the kungfu above and happily continue developing.

**Comment by lhchavez** [comment] 2017-02-15 01:39
yes! using wily for the time being is the Right Way(tm). i'll try this later.

**Comment by lhchavez** [comment] 2017-02-15 03:48
turns out that:

1. I still have the old Wily `.box` in my filesystem, so I can still create Vagrant machines.
1. I can package pre-created VMs into Vagrant `.box`es.
1. My machine is pretty fast, so I can create the `.box` and upload it to S3 for developers to just download and save ~30 minutes of their time.

**Comment by lhchavez** [comment] 2017-02-15 04:41
Fixed by https://github.com/omegaup/deploy/commit/24d93b08a1903ee2a67c06491d6facf111ca7cca . (or rather, will be fixed. the actual image is still being uploaded)

**Closed as completed by lhchavez** 2017-02-15 04:41 UTC

**Comment by joemmanuel** [comment] 2017-02-15 14:33
Thanks! Image is returning 403:
```
...
    default: Downloading: https://s3.amazonaws.com/omegaup-dist/omegaup-wily-2017-base.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 403 Forbidden
```

**Comment by lhchavez** [comment] 2017-02-15 15:12
not anymore ;)

    $ curl --head https://s3.amazonaws.com/omegaup-dist/omegaup-wily-2017-base.box
    HTTP/1.1 200 OK
    x-amz-id-2: uzxFcsWJmy/BnX3quetGQfCUWAFVHTxaqR/EdoO+sE7Q4CKRb7SgZZ7S2uCHmrINJwmQ0o6/KFs=
    x-amz-request-id: EA852B5256CA3A9C
    Date: Wed, 15 Feb 2017 15:11:41 GMT
    Last-Modified: Wed, 15 Feb 2017 05:05:09 GMT
    ETag: "40bb787d9f86c3374c5a22c33efeebaf-44"
    x-amz-meta-s3cmd-attrs: uid:1000/gname:lhchavez/uname:lhchavez/gid:1000/mode:33188/mtime:1487129750/atime:1487129813/md5:57e1dd27411fc4179f457ab756d572d6/ctime:1487130680
    Accept-Ranges: bytes
    Content-Type: application/gzip
    Content-Length: 686184484
    Server: AmazonS3

**Comment by alanboy** [comment] 2017-02-15 17:52
verified it works!
